project:
  type: website

website:
  title: "Ryan C McMurry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
      - href: How (Not) to do Research Blog.qmd
        text: How (Not) to do Research 
      - href: How to (Almost) Travel like a Local.qmd
        text: How to (Almost) Travel like a Local
      - href: Grad School Survival Guide.qmd
        text: Grad School Survival Guide
format:
  html:
    theme: superhero
    toc: true



